---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Vincent.
--- DateTime: 3/8/2021 8:33 PM
---

PauseState = Class{__includes = BaseState}

function PauseState:enter()
end

function PauseState:update(dt)
    if love.keyboard.wasPressed('p') or love.keyboard.wasPressed('return') then
        gStateMachine:change('play')
    end
end

function PauseState:render()
    -- simply render the score to the middle of the screen
    love.graphics.setFont(flappyFont)
    love.graphics.printf('Pause', 0, 64, VIRTUAL_WIDTH, 'center')
end
